### ISSUE TITLE
Use language strings from language i18n file

### ISSUE THREAD

**Issue by Phineas** [waifusion/waifusion-site#67]
As Waifusion expands, we're needing to add support for other languages, namely Japanese, so we can expand our worldwide appeal. There are contributors ready to add translations, so I've created an initial i18n file at src/i18n/strings.js which exports a {[language_code: string]: {[string_name: string]: string}} object to map languages to their respective strings.

With this, we'll also need to add a new function or hook to make it easy to use the current language strings that the user has selected from the file. In a perfect world, we should just be able to include `{lang.WAIFU_NAME_PREFIX}`, for example, in a component and it should work. Open to suggestions on what people think the best way of going about this is.

**Comment by QuantumlyTangled** [comment]
To target a more global audience JSON files may be better since they are supported across more translation platforms. One of them being [Crowdin](https://crowdin.com/) or if you prefer a self-hosted solution there's also [Weblate](https://weblate.org/en/).
As for something to interpret the files, there's an internationalization-framework called [i18next](https://www.i18next.com/) that also offers a React library called [react-i18next](https://react.i18next.com/).
